import type { Metadata } from "next";
import "./globals.css";
import { Bebas_Neue, Poppins, Lato, Open_Sans } from "next/font/google";
import { AppProvider } from '@/provider/state-manager'


const bebas_init = Bebas_Neue({
  subsets: ['latin'],
  weight: ['400'],
  display: "swap",
  variable: '--font-bebas_neue'
});

const open_sans_init = Open_Sans({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800'],
  display: "swap",
  variable: '--font-open_sans'
});

const lato_init = Lato({
  subsets: ['latin'],
  weight: ['400'],
  display: "swap",
  variable: '--font-lato'
});

const poppins_init = Poppins({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  display: "swap",
  variable: '--font-poppins'
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${bebas_init.variable} ${poppins_init.variable} ${lato_init.variable} ${open_sans_init.variable}`}>
        <AppProvider>
        {children}
        </AppProvider>
        </body>
    </html>
  );
}
